"""
╔══════════════════════════════════════════════════════════╗
║   KERALA WAR ROOM 2026 — Auto Setup Script              ║
║   Generates all .env files in one go                    ║
║   Run from project ROOT: python setup.py                ║
╚══════════════════════════════════════════════════════════╝
"""

import os
import sys
from pathlib import Path

# ── Colors for terminal output ────────────────────────────
GREEN  = "\033[92m"
YELLOW = "\033[93m"
RED    = "\033[91m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

def p(msg, color=RESET):   print(f"{color}{msg}{RESET}")
def ok(msg):               print(f"{GREEN}  ✅ {msg}{RESET}")
def warn(msg):             print(f"{YELLOW}  ⚠️  {msg}{RESET}")
def err(msg):              print(f"{RED}  ❌ {msg}{RESET}")
def info(msg):             print(f"{CYAN}  ℹ️  {msg}{RESET}")

# ── Banner ────────────────────────────────────────────────
p("""
╔══════════════════════════════════════════════════════════╗
║        KERALA WAR ROOM 2026 — SETUP WIZARD              ║
╚══════════════════════════════════════════════════════════╝
""", BOLD + CYAN)

# ── Detect project root ───────────────────────────────────
ROOT     = Path(__file__).parent.resolve()
FRONTEND = ROOT / "frontend"
PIPELINE = ROOT / "pipeline"

p(f"📁 Project root : {ROOT}", CYAN)
p(f"📁 Frontend     : {FRONTEND}", CYAN)
p(f"📁 Pipeline     : {PIPELINE}", CYAN)
print()

# ── Validate folder structure ─────────────────────────────
missing = []
if not FRONTEND.exists(): missing.append("frontend/")
if not PIPELINE.exists(): missing.append("pipeline/")
if missing:
    err(f"Missing folders: {', '.join(missing)}")
    err("Make sure you are running this from the kerala-warroom/ root folder.")
    err(f"Current directory: {Path.cwd()}")
    sys.exit(1)

# ── Get API keys from user ────────────────────────────────
p("=" * 56, CYAN)
p("  STEP 1 -- Enter your API keys", BOLD)
p("=" * 56, CYAN)
print()

info("Get your OpenAI key from: https://platform.openai.com/api-keys")
info("Key starts with: sk-proj-...")
print()

while True:
    openai_key = input(f"{YELLOW}  Enter OpenAI API Key: {RESET}").strip()
    if openai_key.startswith("sk-"):
        ok("OpenAI key accepted")
        break
    elif openai_key == "":
        warn("Skipping OpenAI key -- you can add it manually later")
        openai_key = "sk-proj-ADD-YOUR-KEY-HERE"
        break
    else:
        warn("Key should start with 'sk-' -- try again (or press Enter to skip)")

print()

# ── Optional: Anthropic key ───────────────────────────────
info("Optional: Anthropic/Claude key (only if you have credits)")
info("Key starts with: sk-ant-")
print()

anthropic_key = input(
    f"{YELLOW}  Enter Anthropic API Key (or press Enter to skip): {RESET}"
).strip()

if anthropic_key and not anthropic_key.startswith("sk-ant-"):
    warn("Does not look like an Anthropic key -- saving anyway")
if not anthropic_key:
    anthropic_key = "sk-ant-ADD-IF-NEEDED"
    info("Skipped -- OpenAI will be used instead")

print()

# ── Write .env files ──────────────────────────────────────
p("=" * 56, CYAN)
p("  STEP 2 -- Creating .env files", BOLD)
p("=" * 56, CYAN)
print()

ENV_FILES = [
    {
        "path":  ROOT / ".env",
        "label": "Root .env (project-level)",
        "content": (
            "# ==========================================\n"
            "#   KERALA WAR ROOM 2026 -- ROOT .env\n"
            "#   Auto-generated by setup.py\n"
            "# ==========================================\n"
            "\n"
            "# OpenAI (primary -- used by pipeline + frontend)\n"
            f"OPENAI_API_KEY={openai_key}\n"
            "\n"
            "# Anthropic (optional)\n"
            f"ANTHROPIC_API_KEY={anthropic_key}\n"
        ),
    },
    {
        "path":  FRONTEND / ".env",
        "label": "frontend/.env (Vite / React)",
        "content": (
            "# ==========================================\n"
            "#   KERALA WAR ROOM 2026 -- FRONTEND .env\n"
            "#   Auto-generated by setup.py\n"
            "#   VITE_ prefix required for browser access\n"
            "# ==========================================\n"
            "\n"
            "# OpenAI key for Swing Prediction Engine\n"
            f"VITE_OPENAI_API_KEY={openai_key}\n"
            "\n"
            "# Anthropic key (optional)\n"
            f"VITE_ANTHROPIC_API_KEY={anthropic_key}\n"
        ),
    },
    {
        "path":  PIPELINE / ".env",
        "label": "pipeline/.env (Python / LangGraph)",
        "content": (
            "# ==========================================\n"
            "#   KERALA WAR ROOM 2026 -- PIPELINE .env\n"
            "#   Auto-generated by setup.py\n"
            "# ==========================================\n"
            "\n"
            "# OpenAI key for LangGraph pipeline\n"
            f"OPENAI_API_KEY={openai_key}\n"
            "\n"
            "# Anthropic key (optional)\n"
            f"ANTHROPIC_API_KEY={anthropic_key}\n"
            "\n"
            "# Qdrant vector store (optional)\n"
            "QDRANT_HOST=localhost\n"
            "QDRANT_PORT=6333\n"
            "\n"
            "# Telegram alerts (optional)\n"
            "TELEGRAM_BOT_TOKEN=\n"
            "TELEGRAM_CHAT_ID=\n"
        ),
    },
]

for env in ENV_FILES:
    path  = env["path"]
    label = env["label"]
    if path.exists():
        ans = input(
            f"{YELLOW}  {label} already exists. Overwrite? (y/n): {RESET}"
        ).strip().lower()
        if ans != "y":
            warn(f"Skipped: {path}")
            continue
    try:
        path.write_text(env["content"], encoding="utf-8")
        ok(f"Created: {path}")
    except Exception as exc:
        err(f"Failed to create {path}: {exc}")

print()

# ── Verify files ──────────────────────────────────────────
p("=" * 56, CYAN)
p("  STEP 3 -- Verification", BOLD)
p("=" * 56, CYAN)
print()

all_good = True
for env in ENV_FILES:
    path = env["path"]
    if path.exists():
        size = path.stat().st_size
        ok(f"{env['label']}  ({size} bytes)")
        info(f"  {path}")
    else:
        err(f"MISSING: {env['label']}")
        info(f"  Expected at: {path}")
        all_good = False

print()

# ── Next steps ────────────────────────────────────────────
p("=" * 56, CYAN)
p("  NEXT STEPS -- Run these in order", BOLD)
p("=" * 56, CYAN)
print()

steps = [
    ("1", "Terminal 1", "pip install -r pipeline/requirements.txt",
     "Install Python packages (one-time)"),
    ("2", "Terminal 1", "cd frontend && npm install",
     "Install Node packages (one-time)"),
    ("3", "Terminal 2", "cd frontend && npm run dev",
     "Start React dashboard  -->  localhost:5173"),
    ("4", "Terminal 3", "cd pipeline && uvicorn api:app --reload --port 8000",
     "Start FastAPI bridge   -->  localhost:8000"),
    ("5", "Terminal 4", "cd pipeline && python kerala_intelligence_pipeline.py --run-now",
     "Run intelligence pipeline"),
]

for num, term, cmd, desc in steps:
    p(f"  {num}.  [{term}]", BOLD)
    p(f"       $ {cmd}", GREEN)
    p(f"       {desc}", CYAN)
    print()

if all_good:
    p("  All .env files created successfully!", BOLD + GREEN)
else:
    p("  Some files were skipped -- check errors above", BOLD + YELLOW)

p("\n  Kerala War Room 2026 is ready to launch!\n", BOLD + CYAN)
